### ISSUE TITLE
Registering applications to use Viagogo APIs

### ISSUE THREAD

**Issue by spinach** [viagogo/developer.viagogo.net#24]
Hello,

Not sure if this is the right place to post this question, but I couldn't find another way to contact you guys. 

I wanted to play around with the Viagogo API v2, and I read this part:

"All developers need to [register their application](http://developer.viagogo.net/#) before getting started. Registered applications are assigned a unique Client ID and Client Secret that are required for authentication."

The "register their application" redirects to  developer.viagogo.net, and I cannot find the place where I can register my application in order to get cliend_id and client secret. Can someone point me in the right direction?

Thanks.

**Comment by spinach** [comment]
"Before accessing viagogo APIs, you need to register your application. During the beta period, API access will be available by invitation only."

How can we ask for one?

**Comment by akilb** [comment]
Hi @guydaher. Thanks for getting in touch. You can email affiliates.team@viagogo.com to get set up with API access

**Comment by spinach** [comment]
Thanks!

**Comment by spinach** [comment]
FYI I got no response it s been 10 days..

**Comment by taddison** [comment]
I'm looking into this for you @guydaher

**Comment by taddison** [comment]
Our affiliates team advise they've just sent you a reply - apologies for the delay and thanks for letting us know you were still waiting!

**Comment by spinach** [comment]
Ok Now I know why I didn't get a reply:
Typo in the email your wrote above. The real one is:
Affiliate.Team@viagogo.com (without an s).

And Thanks for contacting them :)

**Comment by noyfactor** [comment]
Hey @taddison, sorry for jumping in here but I've been trying to mail the affiliate team (using @guydaher's corrected email) and no response. Is there a different process I should be using?

**Comment by akilb** [comment]
Hi @noyg,

Sorry for the delay. Can you please send another email and specify your GitHub username (noyg) so that the Affiliate Team can identify the request.

Thanks

**Comment by Basilysk** [comment]
Hi @noyg,

The same on our side. We have contacted the Affiliate Team using the above-mentioned email about 2 weeks ago and still no answer. Is there any chance to reach them?

Thank you very much.

**Comment by noyfactor** [comment]
@akilb Done. Waiting for response. Thank you!
@Basilysk I guess a good idea would be to ask @akilb or @taddison ..

**Comment by Basilysk** [comment]
Hi @taddison, I have the same story as @noyg, hope you can help. Thanks a lot.
@noyg thanks for the advice

**Comment by taddison** [comment]
Hey @Basilysk, can you confirm if you've provided your Github username in your email?  After that I'll speak to our affiliates team.

**Comment by Basilysk** [comment]
Hey @taddison, thank you. I've just sent an email to Affiliate.Team@viagogo.com
with my Github nick in the body.
I am more than happy to provide all the necessary information they might ask for.
Thanks a lot.

**Comment by pawgol** [comment]
Hey @taddison, @akilb
I've been trying to mail the viagogo (Affiliate.Team@viagogo.com, affiliate@viagogo.com) and no response. I'm affiliate partner of Viagogo. Can I get access to the Viagogo API v2?

**Comment by kazaroth** [comment]
Hey @taddison - just stumbled across this thread whilst trying to get API access. Only filled in the online form today, but would be grateful if you could follow it up :)

It's probably submitted on my personal email: kazaroth at gmail.com

**Comment by FedericoSoma** [comment]
Hey we are www.skydreamer.io! We successsfully applied through the Awin platform to became affiliate members. We tried to e-mail you several times to affiliate@viagogo.com and affiliates@viagogo.com without getting a response. Could we get access to your XML/JSON API?  @taddison  @Basilysk

**Comment by jdub4237** [comment]
@taddison @Basilysk - I would like an invitation to your API.  I am emailing now as well and will include my user name in the subject.

**Comment by joseantgv** [comment]
Hi!
I'm also interested in testing your API. I'm going to write you an email. 
Thanks!

**Comment by joseantgv** [comment]
No answer after 15 days :(

CC @akilb @taddison

**Comment by VantaxDev** [comment]
@taddison @Basilysk - I would like to know how i can register my application before using your API. The google docs link is no more valid and... I'm wondering how can I bypass this step. 
I am emailing now as well and will include my user name in the subject. best regards

**Comment by joseantgv** [comment]
@VantaxDev Good luck, it was impossible for me to get a response

**Comment by Name-less** [comment]
Some news on this thread ? @joseantgv

**Comment by joseantgv** [comment]
@Name-less Nope

**Comment by ticktack7** [comment]
Hello,
I wrote you an email for registration.
Thanks in advance

**Comment by erzegoto** [comment]
Up. I sent an email both of affiliate.team@viagogo.com and affiliate@viagogo.com
Thank you

**Comment by fkubala** [comment]
same as @erzegoto , sent message on affiliate.team@viagogo.com and affiliate@viagogo.com
Thanks for any answer

**Comment by joseantgv** [comment]
Good luck!

**Comment by ticktack7** [comment]
Hello everyone, did anyone suceed to access the viagogo API ?
It has been a year now, and no answer.

**Comment by Anton-V-K** [comment]
These days the [Quick Reference page](https://developer.viagogo.net/#quick-reference) still says: 

> Before accessing viagogo APIs, you need to register your application. During the beta period, API access will be available by invitation only.

3+ years in Beta... Wow! :)

**Comment by evgentor** [comment]
I sent an email both of affiliate.team@viagogo.com and affiliate@viagogo.com
Thank you!

**Comment by IgorUkolov** [comment]
How do I access API?

**Comment by joseantgv** [comment]
> How do I access API?

Forget it, it's impossible. It's the most opaque company I've never seen.
